package main

import (
	"encoding/json"
	"fmt"
	"log"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"sync"

	"github.com/derekparker/trie/v3"
	"github.com/hashicorp/go-hclog"
	"github.com/hashicorp/go-plugin"
	"github.com/itchyny/gojq"
	"github.com/prometheus/common/version"

	"github.com/openconfig/gnmic/pkg/api/types"
	"github.com/openconfig/gnmic/pkg/formatters"
	"github.com/openconfig/gnmic/pkg/formatters/event_plugin"
)

const (
	processorType = "event-prometheus-processor"
	loggingPrefix = "[" + processorType + "]"
)

type ciscoWLC struct {
	Name          string
	Address       string
	Subscriptions []string
	apWtpMacMap   *sync.Map
	apEthMacMap   *sync.Map
	apTagMap      *sync.Map
}

type confValues struct {
	// Apply the configuration to any event that matches this YANG path
	Match string `mapstructure:"match,omitempty"  yaml:"match,omitempty"  json:"match,omitempty"`
	// Apply the configuration to any value in this list
	Values []string `mapstructure:"values,omitempty" yaml:"values,omitempty" json:"values,omitempty"`
}

type confTagRenames struct {
	// Apply the tag renames to any event that matches this YANG path
	Match string `mapstructure:"match,omitempty"   yaml:"match,omitempty"   json:"match,omitempty"`
	// List of tag renames
	Renames []struct {
		// Original tag name
		From string `mapstructure:"from,omitempty"  yaml:"from,omitempty"  json:"from,omitempty"`
		// New tag name
		To string `mapstructure:"to,omitempty"  yaml:"to,omitempty"  json:"to,omitempty"`
	} `mapstructure:"renames,omitempty" yaml:"renames,omitempty" json:"renames,omitempty"`
}

type confEnumMappings struct {
	// Apply the enum value mappings to any event that matches this YANG path
	Match string `mapstructure:"match,omitempty" yaml:"match,omitempty" json:"match,omitempty"`
	// List of enum value mappings
	Enums []struct {
		// Enum name
		Enum string `mapstructure:"enum,omitempty"  yaml:"enum,omitempty"  json:"enum,omitempty"`
		// List of value mappings
		Mappings []struct {
			// Original string value
			From string `mapstructure:"from,omitempty"  yaml:"from,omitempty"  json:"from,omitempty"`
			// New integer value
			To int `mapstructure:"to,omitempty"  yaml:"to,omitempty"  json:"to,omitempty"`
		} `mapstructure:"mappings,omitempty" yaml:"mappings,omitempty" json:"mappings,omitempty"`
	} `mapstructure:"enums,omitempty" yaml:"enums,omitempty" json:"enums,omitempty"`
}

type prometheusProcessor struct {
	// Name for the instance of the plugin
	Name string `mapstructure:"name,omitempty"                   yaml:"name,omitempty"                   json:"name,omitempty"`
	// JQ expression, the plugin will only modify events for which this expression evaluates to true
	Condition string `mapstructure:"condition,omitempty"              yaml:"condition,omitempty"              json:"condition,omitempty"`
	// Enable debug logging for the plugin
	Debug bool `mapstructure:"debug,omitempty"                  yaml:"debug,omitempty"                  json:"debug,omitempty"`
	// Apply a static prefix to all metrics generated by this plugin
	MetricPrefix string `mapstructure:"metric-prefix,omitempty"          yaml:"metric-prefix,omitempty"          json:"metric-prefix,omitempty"`
	// Write all events received by this plugin to the file path configured
	EventTracePath string `mapstructure:"event-trace-file,omitempty"       yaml:"event-trace-file,omitempty"       json:"event-trace-file,omitempty"`
	// List of target names that should be treated as Cisco WLCs
	CiscoWLCs *[]string `mapstructure:"cisco-wlcs,omitempty"             yaml:"cisco-wlcs,omitempty"             json:"cisco-wlcs,omitempty"`
	// List of tags which must exist for AP metrics
	ApTags *[]string `mapstructure:"ap-tags,omitempty"                yaml:"ap-tags,omitempty"                json:"ap-tags,omitempty"`
	// List of YANG paths, if an event matches one of these then it will bypass the required tags configured in ApTags
	BypassApTags *[]string `mapstructure:"bypass-ap-tags,omitempty"         yaml:"bypass-ap-tags,omitempty"         json:"bypass-ap-tags,omitempty"`
	// List of YANG paths, if an event matches one of these then it will be converted to a single info metric regardless of the type of the values
	MixedInfoMetrics *[]string `mapstructure:"mixed-info-metrics,omitempty"     yaml:"mixed-info-metrics,omitempty"     json:"mixed-info-metrics,omitempty"`
	// List of YANG paths, if an event does not match any of these it will be dropped
	ValueAllowlist *[]string `mapstructure:"value-allowlist,omitempty"        yaml:"value-allowlist,omitempty"        json:"value-allowlist,omitempty"`
	// List of YANG paths, if an event matches any of these it will be dropped
	ValueBlocklist *[]string `mapstructure:"value-blocklist,omitempty"        yaml:"value-blocklist,omitempty"        json:"value-blocklist,omitempty"`
	// List of configuration for renaming tags
	TagRenames *[]confTagRenames `mapstructure:"tag-renames,omitempty"            yaml:"tag-renames,omitempty"            json:"tag-renames,omitempty"`
	// List of configuration for converting values to tags
	ValueTags *[]confValues `mapstructure:"value-tags,omitempty"             yaml:"value-tags,omitempty"             json:"value-tags,omitempty"`
	// List of configuration for converting enum string values to integers
	EnumMappings *[]confEnumMappings `mapstructure:"enum-mappings,omitempty"          yaml:"enum-mappings,omitempty"          json:"enum-mappings,omitempty"`
	// List of configuration for converting integer values to tags
	IntegerInfoMetrics *[]confValues `mapstructure:"integer-info-metrics,omitempty"   yaml:"integer-info-metrics,omitempty"   json:"integer-info-metrics,omitempty"`
	// List of configuration for keeping original value when a value is converted to an info metric
	ValueAndInfoMetrics *[]confValues `mapstructure:"value-and-info-metrics,omitempty" yaml:"value-and-info-metrics,omitempty" json:"value-and-info-metrics,omitempty"`

	eventTraceFile *os.File
	eventTraceLock *sync.Mutex

	wlcs map[string]ciscoWLC

	tagRenames          map[string]map[string]string
	valueTags           map[string][]string
	enumMappings        map[string]map[string]map[string]int
	integerInfoMetrics  map[string][]string
	valueAndInfoMetrics map[string][]string

	condition             *gojq.Code
	targetsConfigs        map[string]*types.TargetConfig
	actionsDefinitions    map[string]map[string]any
	processorsDefinitions map[string]map[string]any
	logger                hclog.Logger
}

func (p *prometheusProcessor) Init(cfg any, opts ...formatters.Option) error {
	err := formatters.DecodeConfig(cfg, p)
	if err != nil {
		return fmt.Errorf("error decoding configuration: %w", err)
	}

	p.setupLogger()

	if p.Condition != "" {
		q, err := gojq.Parse(strings.TrimSpace(p.Condition))
		if err != nil {
			return fmt.Errorf("error parsing jq condition: %w", err)
		}
		p.condition, err = gojq.Compile(q)
		if err != nil {
			return fmt.Errorf("error compiling jq condition: %w", err)
		}
	}

	if p.CiscoWLCs == nil {
		p.CiscoWLCs = &[]string{}
	}

	if p.ApTags == nil {
		p.ApTags = &[]string{}
	}
	if p.BypassApTags == nil {
		p.BypassApTags = &[]string{}
	}
	if p.MixedInfoMetrics == nil {
		p.MixedInfoMetrics = &[]string{}
	}
	if p.ValueAllowlist == nil {
		p.ValueAllowlist = &[]string{}
	}
	if p.ValueBlocklist == nil {
		p.ValueBlocklist = &[]string{}
	}
	for _, cfg := range []*[]string{p.BypassApTags, p.MixedInfoMetrics, p.ValueAllowlist, p.ValueBlocklist} {
		// Strip yang paths
		for i, v := range *cfg {
			stripped := stripYangPathOrigin(v)
			if v != stripped {
				(*cfg)[i] = stripped
			}
		}
	}

	if p.TagRenames != nil {
		// Parse tag rename configuration
		tagRenames := map[string]map[string]string{}
		for _, v := range *p.TagRenames {
			if _, exists := tagRenames[v.Match]; !exists {
				tagRenames[v.Match] = map[string]string{}
			}
			for _, r := range v.Renames {
				tagRenames[v.Match][r.From] = r.To
			}
		}
		p.tagRenames = tagRenames
	}
	for m, v := range p.tagRenames {
		// Strip tag rename yang paths
		stripped := stripYangPathOrigin(m)
		if m != stripped {
			if _, exists := p.tagRenames[stripped]; exists {
				maps.Copy(p.tagRenames[stripped], v)
			} else {
				p.tagRenames[stripped] = v
			}
			delete(p.tagRenames, m)
		}
	}

	if p.ValueTags != nil {
		// Parse value tag configuration
		valueTags := map[string][]string{}
		for _, v := range *p.ValueTags {
			if s, exists := valueTags[v.Match]; exists {
				s = append(s, v.Values...)
				valueTags[v.Match] = s
			} else {
				valueTags[v.Match] = v.Values
			}
		}
		p.valueTags = valueTags
	}
	for m, v := range p.valueTags {
		// Strip value tag yang paths
		stripped := stripYangPathOrigin(m)
		if m != stripped {
			if curr, exists := p.valueTags[stripped]; exists {
				p.valueTags[stripped] = append(curr, v...)
			} else {
				p.valueTags[stripped] = v
			}
			delete(p.valueTags, m)
		}
	}

	if p.EnumMappings != nil {
		// Parse enum mapping configuration
		enumMappings := map[string]map[string]map[string]int{}
		for _, v := range *p.EnumMappings {
			if _, exists := enumMappings[v.Match]; !exists {
				enumMappings[v.Match] = map[string]map[string]int{}
			}
			for _, e := range v.Enums {
				if _, exists := enumMappings[v.Match][e.Enum]; !exists {
					enumMappings[v.Match][e.Enum] = map[string]int{}
				}
				for _, m := range e.Mappings {
					enumMappings[v.Match][e.Enum][m.From] = m.To
				}
			}
		}
		p.enumMappings = enumMappings
	}
	for m, v := range p.enumMappings {
		// Strip enum mapping yang paths
		stripped := stripYangPathOrigin(m)
		if m != stripped {
			if _, exists := p.enumMappings[stripped]; exists {
				maps.Copy(p.enumMappings[stripped], v)
			} else {
				p.enumMappings[stripped] = v
			}
			delete(p.enumMappings, m)
		}
	}

	if p.IntegerInfoMetrics != nil {
		// Parse integer info metric configuration
		integerInfoMetrics := map[string][]string{}
		for _, v := range *p.IntegerInfoMetrics {
			if s, exists := integerInfoMetrics[v.Match]; exists {
				s = append(s, v.Values...)
				integerInfoMetrics[v.Match] = s
			} else {
				integerInfoMetrics[v.Match] = v.Values
			}
		}
		p.integerInfoMetrics = integerInfoMetrics
	}
	for m, v := range p.integerInfoMetrics {
		// Strip integer info metric yang paths
		stripped := stripYangPathOrigin(m)
		if m != stripped {
			if curr, exists := p.integerInfoMetrics[stripped]; exists {
				p.integerInfoMetrics[stripped] = append(curr, v...)
			} else {
				p.integerInfoMetrics[stripped] = v
			}
			delete(p.integerInfoMetrics, m)
		}
	}

	if p.ValueAndInfoMetrics != nil {
		// Parse value and info metric configuration
		valueAndInfoMetrics := map[string][]string{}
		for _, v := range *p.ValueAndInfoMetrics {
			if s, exists := valueAndInfoMetrics[v.Match]; exists {
				s = append(s, v.Values...)
				valueAndInfoMetrics[v.Match] = s
			} else {
				valueAndInfoMetrics[v.Match] = v.Values
			}
		}
		p.valueAndInfoMetrics = valueAndInfoMetrics
	}
	for m, v := range p.valueAndInfoMetrics {
		// Strip value and info metric yang paths
		stripped := stripYangPathOrigin(m)
		if m != stripped {
			if curr, exists := p.valueAndInfoMetrics[stripped]; exists {
				p.valueAndInfoMetrics[stripped] = append(curr, v...)
			} else {
				p.valueAndInfoMetrics[stripped] = v
			}
			delete(p.valueAndInfoMetrics, m)
		}
	}

	p.wlcs = map[string]ciscoWLC{}
	for _, t := range p.targetsConfigs {
		if !slices.Contains(*p.CiscoWLCs, t.Name) {
			continue
		}
		// Add struct to store cisco wlc state
		wlc := ciscoWLC{
			Name:          t.Name,
			Address:       t.Address,
			Subscriptions: t.Subscriptions,
			apWtpMacMap:   &sync.Map{},
			apEthMacMap:   &sync.Map{},
			apTagMap:      &sync.Map{},
		}
		p.logger.Info("adding cisco wlc", "name", wlc.Name)
		p.wlcs[wlc.Name] = wlc
	}

	if p.EventTracePath != "" {
		p.logger.Info("writing events to trace file", "file", p.EventTracePath)
		p.eventTraceLock = &sync.Mutex{}
		f, err := os.OpenFile(p.EventTracePath, os.O_CREATE|os.O_WRONLY, 0644)
		if err != nil {
			return fmt.Errorf("error opening event trace file %s: %w", p.EventTracePath, err)
		}
		p.eventTraceFile = f
	}

	return nil
}

func (p *prometheusProcessor) Apply(events ...*formatters.EventMsg) []*formatters.EventMsg {
	if len(events) == 0 {
		return events
	}

	if p.eventTraceFile != nil {
		p.eventTraceLock.Lock()

		json, err := json.MarshalIndent(events, "", "  ")
		if err != nil {
			p.logger.Error("error marshalling events to json")
		} else {
			if _, err := p.eventTraceFile.Write(json); err != nil {
				p.logger.Error("error writing to event trace file")
			}
			if _, err := p.eventTraceFile.WriteString("\n\n"); err != nil {
				p.logger.Error("error writing to event trace file")
			}
		}

		p.eventTraceLock.Unlock()
	}

	matchedEvents, unmatchedEvents, err := matchEvents(events, p.condition)
	if err != nil {
		p.logger.Error("error while matching events", "error", err.Error())
	}

	if l := len(matchedEvents); l >= 1 {
		p.logger.Debug("found events to process", "events", l)
	} else {
		p.logger.Debug("no events to process")
	}

	if l := len(unmatchedEvents); l >= 1 {
		p.logger.Debug("found events to ignore", "events", l)
	}

	eventTrees := []*trie.Trie[*formatters.EventMsg]{}
	for _, e := range groupEventsByTag(splitEventsByJSONArray(matchedEvents)) {
		e.Tags = stripTags(e.Tags)

		e.Values = removeValues(
			*p.ValueBlocklist,
			*p.ValueAllowlist,
			e.Values,
		)

		eventTree, err := eventToTree(e)
		if err != nil {
			p.logger.Warn(
				"error converting event to tree",
				"event", e.Name,
				"tags", tagsToString(e.Tags),
				"error", err.Error(),
			)
		}
		eventTrees = append(eventTrees, eventTree)
	}

	// YANG paths that contain additional metadata that we want to consume
	metaNodes := []string{
		"Cisco-IOS-XE-wireless-access-point-oper:access-point-oper-data/ap-name-mac-map",
		"Cisco-IOS-XE-wireless-ap-cfg:ap-cfg-data/ap-tags/ap-tag",
		"Cisco-IOS-XE-wireless-ap-cfg:ap-cfg-data/location-entries/location-entry/associated-aps/associated-ap",
	}

	// Find metadata nodes and store metadata in a lookup table
	for _, eventTree := range eventTrees {
		for _, metaNode := range metaNodes {
			node, exists := eventTree.Find(metaNode)
			if !exists {
				continue
			}

			e := node.Val()

			for _, yangPath := range e.Deletes {
				switch stripYangPathNamespace(yangPath) {
				case "access-point-oper-data/ap-name-mac-map":
					// AP has been removed from the WLC
					if apName, exists := e.Tags["wtp-name"]; exists {
						wlc, err := p.getCiscoWLC(e)
						if err != nil {
							continue
						}
						p.logger.Debug("removing ap", "wlc", wlc.Name, "ap", apName)
						if tags, exists := wlc.apTagMap.Load(apName); exists {
							if t, ok := tags.(*sync.Map); ok {
								if wtpMac, exists := t.Load("wtp-mac"); exists {
									wlc.apWtpMacMap.Delete(wtpMac)
								}
								if apMac, exists := t.Load("ap-mac"); exists {
									wlc.apEthMacMap.Delete(apMac)
								}
							}
						}
						wlc.apTagMap.Delete(apName)
					}
				}
			}

			valuesToRemove := []string{}

			for dir, vals := range mergeValues(e.Values) {
				switch stripYangPathNamespace(dir) {
				case "access-point-oper-data/ap-name-mac-map":
					// AP has been added to the WLC
					if !slices.Contains(valuesToRemove, dir) {
						valuesToRemove = append(valuesToRemove, dir)
					}
					if apName, exists := e.Tags["wtp-name"]; exists {
						wlc, err := p.getCiscoWLC(e)
						if err != nil {
							continue
						}
						p.logger.Debug(
							"adding ap",
							"wlc",
							wlc.Name,
							"ap-name",
							apName,
							"wtp-mac",
							vals["wtp-mac"],
							"eth-mac",
							vals["eth-mac"],
						)
						if wtpMac, exists := vals["wtp-mac"]; exists {
							// Store mapping from wtp-mac to ap-name
							wlc.apWtpMacMap.Store(wtpMac, apName)
							tags, _ := wlc.apTagMap.LoadOrStore(apName, &sync.Map{})
							if t, ok := tags.(*sync.Map); ok {
								t.Store("ap-mac", wtpMac)
							}
						}
						if ethMac, exists := vals["eth-mac"]; exists {
							// Store mapping from eth-mac to ap-name
							wlc.apEthMacMap.Store(ethMac, apName)
							tags, _ := wlc.apTagMap.LoadOrStore(apName, &sync.Map{})
							if t, ok := tags.(*sync.Map); ok {
								t.Store("eth-mac", ethMac)
							}
						}
					}
				case "ap-cfg-data/ap-tags/ap-tag":
					// Tag metadata for an AP
					if !slices.Contains(valuesToRemove, dir) {
						valuesToRemove = append(valuesToRemove, dir)
					}
					if ethMac, exists := e.Tags["ap-mac"]; exists {
						if siteTag, exists := vals["site-tag"]; exists {
							wlc, err := p.getCiscoWLC(e)
							if err != nil {
								continue
							}
							if apName, exists := wlc.apEthMacMap.Load(ethMac); exists {
								// Store mapping from ap-name to site-tag
								tags, _ := wlc.apTagMap.LoadOrStore(apName, &sync.Map{})
								if t, ok := tags.(*sync.Map); ok {
									t.Store("site-tag", siteTag)
								}
							}
						}
					}
				case "ap-cfg-data/location-entries/location-entry/associated-aps/associated-ap":
					// Location metadata for an AP
					if !slices.Contains(valuesToRemove, dir) {
						valuesToRemove = append(valuesToRemove, dir)
					}
					if ethMac, exists := e.Tags["ap-mac"]; exists {
						if locationName, exists := e.Tags["location-name"]; exists {
							wlc, err := p.getCiscoWLC(e)
							if err != nil {
								continue
							}
							if apName, exists := wlc.apEthMacMap.Load(ethMac); exists {
								// Store mapping from ap-name to location-name
								tags, _ := wlc.apTagMap.LoadOrStore(apName, &sync.Map{})
								if t, ok := tags.(*sync.Map); ok {
									t.Store("location-name", locationName)
								}
							}
						}
					}
				}
			}

			// Remove values that we just consumed metadata from
			e.Values = removeValues(
				valuesToRemove,
				[]string{},
				e.Values,
			)
		}
	}

	transformedEvents := []*formatters.EventMsg{}

	// Transform event values and create info metrics
	for _, eventTree := range eventTrees {
		for node, e := range eventTree.PrefixSearchIter("") {
			if len(e.Values) == 0 {
				continue
			}

			// Convert values to tags based on ValueTags configuration
			for k, v := range e.Values {
				dir := filepath.Dir(k)
				base := filepath.Base(k)
				for _, matcher := range getYangPathMatchers(dir) {
					if valueTags, exists := p.valueTags[matcher]; exists {
						if slices.Contains(valueTags, base) {
							s := fmt.Sprintf("%v", v)
							if s != "" {
								// Propegate new tag to child events
								for _, subEvent := range eventTree.PrefixSearchIter(node) {
									if err := addTag(subEvent.Tags, base, s); err != nil {
										p.logger.Warn(
											"error updating sibling or child event tag",
											"event", e.Name,
											"tags", tagsToString(e.Tags),
											"error", err.Error(),
										)
									}
								}
								delete(e.Values, k)
								break
							}
						}
					}
				}
			}

			infoMetrics := []*formatters.EventMsg{}

			// Convert timestamp and enum string values to integers
			for k, v := range e.Values {
				matched := false

				if s, ok := v.(string); ok {
					// Convert timestamps to unixtime
					if t, match, err := parseTimestamp(s); match {
						if err != nil {
							p.logger.Error(
								"error parsing timestamp",
								"event", e.Name,
								"tags", tagsToString(e.Tags),
								"error", err.Error(),
							)
							delete(e.Values, k)
						} else {
							matched = true
							e.Values[k] = t.Unix()
						}
					} else {
						// Parse enum strings to integers based on EnumMappings configuration
						if n, match, err := parseEnum(k, s, p.enumMappings); match {
							if err != nil {
								p.logger.Error(
									"error converting enum to integer",
									"event", e.Name,
									"tags", tagsToString(e.Tags),
									"error", err.Error(),
								)
								delete(e.Values, k)
							} else {
								matched = true
								e.Values[k] = n
							}
						}
					}

					if matched {
						keep := false
						dir := filepath.Dir(k)
						base := filepath.Base(k)
						for _, matcher := range getYangPathMatchers(dir) {
							if valAndInfoMetric, exists := p.valueAndInfoMetrics[matcher]; exists {
								if slices.Contains(valAndInfoMetric, base) {
									keep = true
									break
								}
							}
						}

						if keep {
							// Add info metric for original string value
							// if configured in ValueAndInfoMetrics
							infoMetricTags := map[string]string{}
							maps.Copy(infoMetricTags, e.Tags)

							if err := addTag(infoMetricTags, base, s); err != nil {
								p.logger.Warn(
									"error updating info metric tag",
									"event", e.Name,
									"tags", tagsToString(e.Tags),
									"error", err.Error(),
								)
							} else {
								infoMetricName := k
								if !strings.HasSuffix(infoMetricName, "-info") {
									infoMetricName += "/info"
								}

								infoMetrics = append(infoMetrics, &formatters.EventMsg{
									Name:      e.Name,
									Timestamp: e.Timestamp,
									Tags:      infoMetricTags,
									Values: map[string]any{
										infoMetricName: 1,
									},
								})
							}
						}
					}
				}
			}

			// Create info metrics
			for dir, vals := range mergeValues(e.Values) {
				infoMetricName := ""
				infoMetricTags := map[string]string{}
				maps.Copy(infoMetricTags, e.Tags)

				if slices.Contains(*p.MixedInfoMetrics, dir) ||
					slices.Contains(*p.MixedInfoMetrics, stripYangPathNamespace(dir)) {
					infoMetricName = dir

					// Add info metric with all values converted to strings
					// if configured in MixedInfoMetrics
					for k, v := range vals {
						s := fmt.Sprintf("%v", v)
						if s == "" {
							continue
						}

						if err := addTag(infoMetricTags, k, s); err != nil {
							p.logger.Warn(
								"error updating info metric tag",
								"event", e.Name,
								"tags", tagsToString(e.Tags),
								"error", err.Error(),
							)
						} else {
							delete(e.Values, dir+"/"+k)
						}
					}
				} else {
					for k, v := range vals {
						var strVal string

						switch s := v.(type) {
						case string:
							strVal = s
						default:
							// Treat value as string if configured
							// in IntegerInfoMetrics
							for _, matcher := range getYangPathMatchers(dir) {
								if intInfoMetric, exists := p.integerInfoMetrics[matcher]; exists {
									if slices.Contains(intInfoMetric, k) {
										strVal = fmt.Sprintf("%v", v)
										break
									}
								}
							}
						}

						if strVal != "" {
							// Add string value to info metric
							if err := addTag(infoMetricTags, k, strVal); err != nil {
								p.logger.Warn(
									"error updating info metric tag",
									"event", e.Name,
									"tags", tagsToString(e.Tags),
									"error", err.Error(),
								)
							} else {
								keep := false
								for _, matcher := range getYangPathMatchers(dir) {
									// Keep original value if
									// configured in ValueAndInfoMetrics
									if valAndInfoMetric, exists := p.valueAndInfoMetrics[matcher]; exists {
										if slices.Contains(valAndInfoMetric, k) {
											keep = true
											break
										}
									}
								}

								if !keep {
									delete(e.Values, dir+"/"+k)
								}
							}

							if len(vals) == 1 {
								infoMetricName = dir + "/" + k
							} else {
								infoMetricName = dir
							}
						}
					}
				}

				if infoMetricName != "" && len(infoMetricTags) >= 1 {
					if !strings.HasSuffix(infoMetricName, "-info") {
						infoMetricName += "/info"
					}

					infoMetrics = append(infoMetrics, &formatters.EventMsg{
						Name:      e.Name,
						Timestamp: e.Timestamp,
						Tags:      infoMetricTags,
						Values: map[string]any{
							infoMetricName: 1,
						},
					})
				}
			}

			transformedEvents = append(transformedEvents, infoMetrics...)

			if len(e.Tags) >= 1 && len(e.Values) >= 1 {
				transformedEvents = append(transformedEvents, e)
			}
		}
	}

	processedEvents := []*formatters.EventMsg{}

	// Modify tags and strip values
	for _, e := range transformedEvents {
		// Rename tags based on TagRenames configuration
		var err error
		e.Tags, err = renameTags(e.Name, e.Tags, p.tagRenames)
		if err != nil {
			p.logger.Warn(
				"error renaming tags",
				"event", e.Name,
				"tags", tagsToString(e.Tags),
				"error", err.Error(),
			)
		}

		e.Values = stripValues(e.Values, p.MetricPrefix)

		// Convert mac address to ap-name using lookup table
		if _, exists := e.Tags["ap-name"]; !exists {
			bypass := false
			for _, matcher := range getYangPathMatchers(e.Name) {
				if slices.Contains(*p.BypassApTags, matcher) {
					bypass = true
					break
				}
			}

			// Only do mac lookup for events not configured in BypassApTags
			if !bypass {
				if apMac, exists := e.Tags["ap-mac"]; exists {
					wlc, err := p.getCiscoWLC(e)
					if err != nil {
						continue
					}

					if apName, exists := wlc.apWtpMacMap.Load(apMac); exists {
						s := fmt.Sprintf("%s", apName)
						if err := addTag(e.Tags, "ap-name", s); err != nil {
							p.logger.Warn(
								"error updating ap-name tag",
								"event", e.Name,
								"tags", tagsToString(e.Tags),
								"error", err.Error(),
							)
						}
					} else {
						p.logger.Warn("ap-name is missing", "event", e.Name, "tags", tagsToString(e.Tags))
						continue
					}
				} else if wtpMac, exists := e.Tags["wtp-mac"]; exists {
					wlc, err := p.getCiscoWLC(e)
					if err != nil {
						continue
					}

					if apName, exists := wlc.apWtpMacMap.Load(wtpMac); exists {
						s := fmt.Sprintf("%s", apName)
						if err := addTag(e.Tags, "ap-name", s); err != nil {
							p.logger.Warn(
								"error updating ap-name tag",
								"event", e.Name,
								"tags", tagsToString(e.Tags),
								"error", err.Error(),
							)
						}
						delete(e.Tags, "wtp-mac")
					} else {
						p.logger.Warn("ap-name is missing", "event", e.Name, "tags", tagsToString(e.Tags))
						continue
					}
				} else if ethMac, exists := e.Tags["eth-mac"]; exists {
					wlc, err := p.getCiscoWLC(e)
					if err != nil {
						continue
					}

					if apName, exists := wlc.apEthMacMap.Load(ethMac); exists {
						s := fmt.Sprintf("%s", apName)
						if err := addTag(e.Tags, "ap-name", s); err != nil {
							p.logger.Warn(
								"error updating ap-name tag",
								"event", e.Name,
								"tags", tagsToString(e.Tags),
								"error", err.Error(),
							)
						}
						delete(e.Tags, "eth-mac")
					} else {
						p.logger.Warn("ap-name is missing", "event", e.Name, "tags", tagsToString(e.Tags))
						continue
					}
				}
			}
		}

		// Apply ap tags for ap events with an ap-name tag
		if apName, exists := e.Tags["ap-name"]; exists {
			bypass := false
			for _, matcher := range getYangPathMatchers(e.Name) {
				if slices.Contains(*p.BypassApTags, matcher) {
					bypass = true
					break
				}
			}

			// Only apply ap tags for events not configured in BypassApTags
			if !bypass {
				wlc, err := p.getCiscoWLC(e)
				if err != nil {
					continue
				}

				if tags, exists := wlc.apTagMap.Load(apName); exists {
					valid := true
					for _, tag := range *p.ApTags {
						// Ensure all tags configured in ApTags are applied
						// to this event
						if _, exists := e.Tags[tag]; exists {
							continue
						}
						if t, ok := tags.(*sync.Map); ok {
							if v, exists := t.Load(tag); exists {
								s := fmt.Sprintf("%s", v)
								if err := addTag(e.Tags, tag, s); err != nil {
									p.logger.Warn(
										"error updating ap tag",
										"event", e.Name,
										"tags", tagsToString(e.Tags),
										"error", err.Error(),
									)
								}
							} else {
								p.logger.Warn(
									"stored tag is missing for ap",
									"event", e.Name,
									"tags", tagsToString(e.Tags),
									"missing-tag", tag,
									"ap-name", apName,
								)
								valid = false
								break
							}
						}
					}
					if !valid {
						continue
					}
				} else {
					p.logger.Warn("no stored tags for ap", "event", e.Name, "tags", tagsToString(e.Tags), "ap-name", apName)
					continue
				}
			}
		}

		processedEvents = append(processedEvents, e)
	}

	// Return our processed events and events that were ignored
	return slices.Concat(processedEvents, unmatchedEvents)
}

func (p *prometheusProcessor) WithActions(act map[string]map[string]any) {
	p.actionsDefinitions = act
}

func (p *prometheusProcessor) WithTargets(tcs map[string]*types.TargetConfig) {
	p.targetsConfigs = tcs
}

func (p *prometheusProcessor) WithProcessors(procs map[string]map[string]any) {
	p.processorsDefinitions = procs
}

func (p *prometheusProcessor) WithLogger(l *log.Logger) {
}

func (p *prometheusProcessor) setupLogger() {
	prefix := loggingPrefix
	if p.Name != "" {
		prefix += " [" + p.Name + "]"
	}
	p.logger = hclog.New(&hclog.LoggerOptions{
		Name:       prefix,
		Output:     os.Stderr,
		TimeFormat: "2006/01/02 15:04:05.999999",
	})
	if p.Debug {
		p.logger.SetLevel(hclog.Debug)
	}
}

// Get the CiscoWLC struct for a given event.
func (p *prometheusProcessor) getCiscoWLC(event *formatters.EventMsg) (ciscoWLC, error) {
	source, exists := event.Tags["source"]
	if !exists {
		p.logger.Error(
			"source tag missing for event",
			"event",
			event.Name,
			"tags",
			tagsToString(event.Tags),
		)
		return ciscoWLC{}, ErrMissingSourceTag
	}

	wlc, exists := p.wlcs[source]
	if !exists {
		p.logger.Error(
			"source not configured as cisco wlc",
			"event", event.Name,
			"tags", tagsToString(event.Tags),
		)
		return ciscoWLC{}, ErrSourceNotCiscoWLC
	}

	return wlc, nil
}

func main() {
	logger := hclog.New(&hclog.LoggerOptions{
		Output:      os.Stderr,
		DisableTime: true,
	})

	logger.Info(
		"starting plugin processor",
		"name",
		processorType,
		"version",
		version.Version,
		"build_date",
		version.BuildDate,
	)

	plug := &prometheusProcessor{}
	plugin.Serve(&plugin.ServeConfig{
		HandshakeConfig: plugin.HandshakeConfig{
			ProtocolVersion:  1,
			MagicCookieKey:   "GNMIC_PLUGIN",
			MagicCookieValue: "gnmic",
		},
		Plugins: map[string]plugin.Plugin{
			processorType: &event_plugin.EventProcessorPlugin{Impl: plug},
		},
		Logger: logger,
	})

	if plug.eventTraceFile != nil {
		if err := plug.eventTraceFile.Close(); err != nil {
			logger.Error("error closing event trace file")
		}
	}

	logger.Info("reached END", "name", processorType)
}
